version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami'

volumes:
  postgresql_data:
    driver: local
